pipeline {
    agent any
    environment{
        IMAGE_NAME = "learn-spring-app"
    }
    stages{
        stage('Initialize - Requirements Check'){
            steps{
                sh 'java -version'
                sh 'mvn -v'
                sh 'docker version'
                echo 'Requirements check completed'
            }
        }
        stage('Cleanup and Test'){
            steps{
                sh 'mvn clean'
                sh 'mvn test'
            }
        }
    }
}